# ZSH Environment Setup

[ -f ".devcontainer/README.md" ] && termd .devcontainer/README.md

alias bundle="docker-compose exec web bundle"
alias psql="docker-compose exec db psql"
alias rack="docker-compose exec web rack"
alias rails="docker-compose exec web rails"
alias rspec="docker-compose exec web rspec"
alias rubocop="docker-compose exec web rubocop"
alias yarn="docker-compose exec web yarn"
